//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testpurpos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date1 
        { 
             get{return Dateformate} 
             set
             { 
                   Date d = Date(yyyy-mm-dd);
                   if(Dateformate == d)
                   {
                     Dateformate = d.DayofWeek;
                   }

             }
        }


        
    }
}
